export default {
  INPUT_CHANGED: 'INPUT_CHANGED',
  OCCUPATION_LIST_FETCHED: 'OCCUPATION_LIST_FETCHED',
  TOGGLE_NOTIFICATION: 'TOGGLE_NOTIFICATION',
  API_REQUEST_START: 'API_REQUEST_START',
  API_REQUEST_SUCCESSFUL: 'API_REQUEST_SUCCESSFUL',
  API_REQUEST_FAILED: 'API_REQUEST_FAILED'
}
